# Fetch S&P 500 / Asset Data & Setup SQL Schema

Financial Markets & Risk Analytics 

This notebook fetches historical asset prices using `yfinance`, computes daily log returns, and constructs a PostgreSQL \
shcema to stoe price histories and analytical returns.

### Import Dependencies

In [9]:
import pandas as pd
import numpy as np
import yfinance as yf
from sqlalchemy import create_engine

### Database Connection

In [10]:
DB_URL = "postgresql://postgres:postNW@localhost:5432/portfolio_db"
engine = create_engine(DB_URL)

### Fetch Historical Stock & Index Data

In [12]:
# disable yfinance internal SQLite cache to prevent lock errors
yf.set_tz_cache_location("/tmp/yf_cache")

# Tickers representing diverse asset classes
# (S&P 500, NASDAQ, Gold, US Treasury Yields)
tickers = ["SPY", "QQQ", "GLD", "TLT"] 
start_date = "2021-01-01"
end_date = "2026-01-01"

# Download daily adjusted close prices
df_download = yf.download(
    tickers, start = start_date, end = end_date, progress = False
)

# Extract adjusted close prices regardless of yfinance version
if "Adj Close" in df_download.columns.levels[0]:
    df_raw = df_download["Adj Close"]
else:
    df_raw = df_download["Close"]

df_raw = df_raw.reset_index().melt(
    id_vars = ["Date"], var_name = "ticker", value_name = "adj_close"
)

df_raw.rename(columns = {"Date": "price_date"}, inplace = True)

# Drop any remaining NaN rows from missing dates
df_raw = df_raw.dropna(subset = ["adj_close"]).reset_index(drop = True)

print(f"Downloaded {len(df_raw):,} total daily price records.")
df_raw.head(10)

Downloaded 5,020 total daily price records.

  price_date ticker   adj_close
0 2021-01-04    GLD  182.330002
1 2021-01-05    GLD  182.869995
2 2021-01-06    GLD  179.899994
3 2021-01-07    GLD  179.479996
4 2021-01-08    GLD  173.339996
5 2021-01-11    GLD  173.000000
6 2021-01-12    GLD  174.119995
7 2021-01-13    GLD  173.369995
8 2021-01-14    GLD  173.279999
9 2021-01-15    GLD  171.130005

### Calculate Log Returns & Write to PostgreSQL

In [13]:
# Sort by ticker and date
df_raw = df_raw.sort_values(by = ["ticker", "price_date"]).reset_index(drop = True)

# Compute daily log returns: r_t = ln(P_t / P_{t-1})
df_raw["prev_close"] = df_raw.groupby("ticker")["adj_close"].shift(1)
df_raw["log_return"] = np.log(df_raw["adj_close"] / df_raw["prev_close"])

# Drop initial NaN rows from lagging
df_market = df_raw.dropna().reset_index(drop = True)

# Export to PostgreSQL
df_market.to_sql("market_prices", engine, if_exists = "replace", index = False)

print("Market price data successfully stored in PostgreSQL table 'market_prices'")
df_market.head(10)

Market price data successfully stored in PostgreSQL table 'market_prices'

  price_date ticker   adj_close  prev_close  log_return
0 2021-01-05    GLD  182.869995  182.330002    0.002957
1 2021-01-06    GLD  179.899994  182.869995   -0.016374
2 2021-01-07    GLD  179.479996  179.899994   -0.002337
3 2021-01-08    GLD  173.339996  179.479996   -0.034809
4 2021-01-11    GLD  173.000000  173.339996   -0.001963
5 2021-01-12    GLD  174.119995  173.000000    0.006453
6 2021-01-13    GLD  173.369995  174.119995   -0.004317
7 2021-01-14    GLD  173.279999  173.369995   -0.000519
8 2021-01-15    GLD  171.130005  173.279999   -0.012485
9 2021-01-19    GLD  172.580002  171.130005    0.008437